# Generated by Django 5.2.3 on 2025-06-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='serial_key',
            field=models.IntegerField(default=11, max_length=8),
            preserve_default=False,
        ),
    ]
