# Generated by Django 5.2.3 on 2025-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_serial_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(max_length=8)),
                ('part_name', models.CharField(max_length=60)),
                ('part_price', models.FloatField()),
                ('opening_qty', models.IntegerField()),
                ('remaining_qty', models.IntegerField()),
            ],
        ),
    ]
