# Generated by Django 5.2.3 on 2025-06-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_addspareparts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(max_length=8)),
                ('part_name', models.CharField(max_length=60)),
                ('part_price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='servicehis',
            name='parts_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='core.addspareparts'),
        ),
    ]
