# Generated by Django 5.2.3 on 2025-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchaseformmodel_alter_servicehis_parts_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addspareparts',
            name='remaining_qty',
        ),
        migrations.AddField(
            model_name='servicehis',
            name='opening_qty',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
