# Generated by Django 6.0.1 on 2026-01-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_addspareparts_remaining_qty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSpareParts',
            new_name='SparePart',
        ),
        migrations.RenameModel(
            old_name='PurchaseFormModel',
            new_name='PurchaseOrder',
        ),
        migrations.AlterField(
            model_name='customer',
            name='serial_key',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.RenameModel(
            old_name='ServiceHis',
            new_name='ServiceRecord',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='parts_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='core.sparepart'),
        ),
    ]
