# Generated by Django 5.2.3 on 2026-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sparepart_rename_purchaseformmodel_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='serial_number',
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
